# Generated by Django 2.1 on 2019-02-01 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('uuid', models.CharField(editable=False, max_length=64, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('name', models.CharField(max_length=64)),
                ('account', models.CharField(help_text='Bank account of the contact', max_length=64)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
    ]
