# Generated by Django 2.1.7 on 2019-03-10 21:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('uuid', models.CharField(editable=False, max_length=64, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=4, unique=True)),
                ('name', models.CharField(max_length=32)),
                ('type', models.CharField(choices=[('profit_loss', 'On profit/loss sheet'), ('balance', 'On balance sheet')], help_text='Where to put the account', max_length=16)),
                ('debit_type', models.CharField(choices=[('debit', 'Debit'), ('credit', 'Credit')], help_text='For profit/loss accounts: debit=cost, credit=profit. For balance accounts: debit=active, credit=passive', max_length=16)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='ChartOfAccounts',
            fields=[
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('uuid', models.CharField(editable=False, max_length=64, primary_key=True, serialize=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='account',
            name='chart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='accounts.ChartOfAccounts'),
        ),
        migrations.AddField(
            model_name='account',
            name='contact',
            field=models.ForeignKey(blank=True, default=None, help_text='Linked contact, in use for debitors and creditors', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='accounts', to='contacts.Contact'),
        ),
    ]
