# Generated by Django 2.1.7 on 2019-03-10 21:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ledger',
            fields=[
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('uuid', models.CharField(editable=False, max_length=64, primary_key=True, serialize=False)),
                ('year', models.IntegerField()),
                ('chart', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ledgers', to='accounts.ChartOfAccounts')),
            ],
            options={
                'ordering': ['chart', 'year'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('uuid', models.CharField(editable=False, max_length=64, primary_key=True, serialize=False)),
                ('date', models.DateField(help_text='Transaction date')),
                ('description', models.CharField(help_text='Long description of the transaction', max_length=128)),
                ('invoice_number', models.CharField(blank=True, default='', help_text='Invoice number from invoicee', max_length=32)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('contact', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='contacts.Contact')),
                ('credit_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credit_transactions', to='accounts.Account')),
                ('debit_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='debit_transactions', to='accounts.Account')),
                ('ledger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='ledger.Ledger')),
            ],
            options={
                'ordering': ['date', 'description'],
            },
        ),
    ]
