# Generated by Django 2.1 on 2019-02-01 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('uuid', models.CharField(editable=False, max_length=64, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('code', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=32, unique=True)),
                ('type', models.CharField(choices=[('profit_loss', 'On profit/loss sheet'), ('balance', 'On balance sheet')], help_text='Where to put the account', max_length=16)),
                ('debit_type', models.CharField(choices=[('debit', 'Debit'), ('credit', 'Credit')], help_text='For profit/loss accounts: debit=cost, credit=profit. For balance accounts: debit=active, credit=passive', max_length=16)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='ChartOfAccounts',
            fields=[
                ('uuid', models.CharField(editable=False, max_length=64, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Ledger',
            fields=[
                ('uuid', models.CharField(editable=False, max_length=64, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('year', models.IntegerField()),
            ],
            options={
                'ordering': ['year'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('uuid', models.CharField(editable=False, max_length=64, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('date', models.DateField(help_text='Transaction date')),
                ('description', models.CharField(help_text='Long description of the transaction', max_length=128)),
                ('invoice_number', models.CharField(blank=True, default='', help_text='Invoice number from invoicee', max_length=32)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('contact', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='contacts.Contact')),
                ('credit_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credit_transactions', to='ledger.Account')),
                ('debit_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='debit_transactions', to='ledger.Account')),
                ('ledger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='ledger.Ledger')),
            ],
            options={
                'ordering': ['date', 'description'],
            },
        ),
        migrations.AddField(
            model_name='account',
            name='chart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='ledger.ChartOfAccounts'),
        ),
        migrations.AddField(
            model_name='account',
            name='contact',
            field=models.ForeignKey(blank=True, default=None, help_text='Linked contact, in use for debitors and creditors', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='accounts', to='contacts.Contact'),
        ),
    ]
